### ISSUE TITLE
Parent Issue: Refactoring of Codebase

### ISSUE THREAD

**Issue by impiyush83** [PalisadoesFoundation/talawa-api#259]
**Is your feature request related to a problem? Please describe.**

This issue is raised to refactor the codebase to increase the readability and future maintainability, Following things could be done to refactor the code and can be worked upon as a child issue individually.

- [x] Error handling with proper error codes - https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
- [x] Logging with proper log levels - https://stackify.com/node-js-logging/
- [x] Async await paradigm instead of Promise -https://itnext.io/javascripts-async-await-versus-promise-the-great-debate-6308cb2e10b3
- [ ] Separating out db methods, business logic from mutations / handlers / controllers 

**Issue Severity**:

 1. Medium 

**Environment Details**:

 1.  Project Level

**Observed Behaviour**:

 1.  I have listed down all the improvements needed for talawa-API codebase refactoring, others are open to raise new proposals

**Expected Behaviour**:

***Solution to problem 1***:

1. Having standardized classes for RequestHandler and ResponseHandler which are reusable. #262
2. Having standardized and meaningful classes to throw meaningful error responses. #263

***Solution to problem 2***:

1. Using logger library for proper logging with proper log levels like` logger.info`, `logger. error` #264

***Solution for problem 3***:

1. Consistently using async-await pattern: #265

***Solution for problem 4***: #266

1.  Controllers / Resolvers  currently this is called as mutation resolvers in **talawa-API** can be reused folder, which will do marshaling, unmarshalling, schema validation of data
2. Services folder, which will mainly deal will business logic
3.  Repositories folder, which will deal with DB calls
4. Having a core folder that will keep track of all the helper, constants, utils, lib files.
